config/routes.rb
Rails.application.routes.draw do
  root 'manuals#index'

  get '/about', to: "manuals#about", as: :about

  resources :manuals do
    collection do
      get :list, as: :list
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/manual.rb
class Manual < ApplicationRecord
  MODES = ["Plane", "Train", "Helicopter"]

  strip_attributes :only => [:carrier, :make, :model, :revision]

  has_permalink :slug

  has_attached_file :photo,
    path: '/:folder/:permalink',
    styles: { large: "1600x", medium: "800x", small: "400x" }

  Paperclip.interpolates :folder do |attachment, style|
    attachment.instance.folder
  end

  Paperclip.interpolates :permalink do |attachment, style|
    attachment.instance.permalink + "-#{style}" + File.extname(attachment.original_filename).downcase
  end

  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  validates :mode, :carrier, :make, :model, presence: true

  scope :by_mode, lambda { |mode| where("mode =  ?", mode) }
  scope :by_make, lambda { |make| where("make = ?", make) }
  scope :by_carrier, lambda { |carrier| where("carrier = ?", carrier) }

  def title
    "#{carrier} #{make} #{model}"
  end

  def slug
    "#{carrier}-#{make}-#{model}-#{revision}"
  end

  def folder
    Rails.env == "development" ? "testing" : "manuals"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/manuals_controller.rb
class ManualsController < ApplicationController
  http_basic_authenticate_with name: ENV['BASIC_AUTH_USERNAME'], password: ENV['BASIC_AUTH_PASSWORD'], only: [:new, :create, :edit, :update, :destroy]
  before_action :set_manual, only: [:show, :edit, :update, :destroy]
  before_action :set_filters, only: [:index, :list]

  def index
    @title = filter_present? ? active_filter : "Home"
    @index_selected = true
  end

  def list
    @title = filter_present? ? "#{active_filter} : Master List" : "Master List"
    @list_selected = true
  end

  def show
    @manual = Manual.find_by(permalink: params[:id])
    @title = @manual.title
  end

  def new
    @title = "New Manual"
    @manual = Manual.new
  end

  def create
    @manual = Manual.new(manual_params)

    if @manual.save
      redirect_to @manual, notice: 'Manual was successfully created.'
    else
      render :new
    end
  end

  def edit
    @title = "Edit Manual - #{@manual.title}"
  end

  def update
    if @manual.update(manual_params)
      redirect_to @manual, notice: 'Manual was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @manual.photo = nil
    @manual.save
    @manual.destroy
    redirect_to manuals_path, notice: 'Manual was successfully destroyed.'
  end

  def about
    @title = "About"
  end

  private

  def filter_present?
    params[:mode].present? || params[:make].present? || params[:carrier].present?
  end

  def active_filter
    params[:mode]&.pluralize || params[:make] || params[:carrier]
  end

  def set_filters
    @manuals = Manual.all.order(:carrier)
    @cleaned_params = {}

    if params[:mode].present?
      @manuals = @manuals.by_mode(params[:mode])
      @cleaned_params.merge!({ mode: params[:mode] })
    end

    if params[:make].present?
      @manuals = @manuals.by_make(params[:make])
      @cleaned_params.merge!({ make: params[:make] })
    end

    if params[:carrier].present?
      @manuals = @manuals.by_carrier(params[:carrier])
      @cleaned_params.merge!({ carrier: params[:carrier] })
    end

    @modes = Manual::MODES
    @makes = Manual.all.pluck(:make).uniq.sort
    @carriers = Manual.all.pluck(:carrier).uniq.sort
  end

  def set_manual
    @manual = Manual.find_by(permalink: params[:id])
  end

  def manual_params
    params.require(:manual).permit(
      :mode,
      :carrier,
      :make,
      :model,
      :revision,
      :photo,
      :notes
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_messages_for(object, attribute, alignment="right")
    if object.errors.messages[attribute].present?
      messages = object.errors.full_messages_for(attribute).join(", ")
      content_tag :p, messages, class: "error-messages-for text-#{alignment}"
    end
  end
end

app/helpers/manuals_helper.rb
module ManualsHelper
end

app/views/admin/manuals/_form.html.erb
<div class="container">
  <div class="col-sm-6 col-sm-offset-3">
    <%= form_for [:admin, manual] do |form| %>

      <div class="form-group">
        <%= form.label :mode %>
        <%= form.select :mode, options_for_select(Manual::MODES, @manual.mode), {}, { id: :manual_mode, class: "form-control input-lg" } %>
      </div>

      <div class="form-group">
        <%= form.label :carrier %>
        <%= form.text_field :carrier, id: :manual_carrier, class: "form-control input-lg" %>
      </div>

      <div class="form-group">
        <%= form.label :make %>
        <%= form.text_field :make, id: :manual_make, class: "form-control input-lg" %>
      </div>

      <div class="form-group">
        <%= form.label :model %>
        <%= form.text_field :model, id: :manual_model, class: "form-control input-lg" %>
      </div>

      <div class="form-group">
        <%= form.label :revision %>
        <%= form.text_field :revision, id: :manual_revision, class: "form-control input-lg" %>
      </div>

      <div class="form-group">
        <%= form.label :notes %>
        <%= form.text_area :notes, id: :manual_notes, class: "form-control input-lg" %>
      </div>

      <div class="form-group">
        <%= form.label :photo %>

        <% if @manual.photo.present? %>
          <%= image_tag(@manual.photo.url(:medium), class: "img-responsive") %>
        <% end %>

        <%= form.file_field :photo, id: :manual_photo, class: "form-control input-lg" %>
      </div>

      <div class="actions">
        <button type="submit" class="btn btn-info input-lg">SAVE</button>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta property="fb:admins" content="elimduke" />
    <meta property="og:type" content="<%= @manual.present? ? "article" : "website" %>" />
    <meta property="og:title" content="<%= @title %> : Safety Manuals" />
    <meta property="og:site_name" content="Safety Manuals"/>
    <meta property="og:url" content="<%= request.url %>" />
    <meta property="og:image" content="<%= @manual.present? ? @manual.photo.url(:large) : "http://safetymanuals.s3.amazonaws.com/furby.png" %>" />
    <meta property="og:description" name="description" content="Safety Manuals are such a funny design exercise, and, if you look close enough, there are all kinds of hilarious little gems buried in them." />

    <title><%= @title %> : Safety Manuals</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div id="header">
      <h1><%= link_to "SAFETY MANUALS", root_path %></h1>
      <p>
        <%= link_to "HOME", manuals_path %> •
        <%= link_to "ABOUT", about_path %> •
        <%= link_to "NEW", new_manual_path %>
      </p>
    </div>

    <%= render partial: "manuals/filters" if action_name.in?(["index", "list"]) %>

    <% if notice %>
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-md-offset-2">
            <p id="notice"><%= notice %></p>
          </div>
        </div>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/manuals/_filters.html.erb
<% filter_on = params[:carrier].present? | params[:make].present? | params[:mode].present? %>

<div id="filters" style="<%= 'display:none' unless filter_on %>">
  <ul class="list-inline modes">
    <li>MODE:</li>
    <% @modes.each do |mode| %>
      <li><%= link_to mode, "?mode=#{mode}" %></li>
    <% end %>
  </ul>

  <ul class="list-inline makes">
    <li>MAKE:</li>
    <% @makes.each do |make| %>
      <li><%= link_to make, "?make=#{make}" %></li>
    <% end %>
  </ul>

  <ul class="list-inline carriers">
    <li>CARRIER:</li>
    <% @carriers.each do |carrier| %>
      <li><%= link_to carrier, "?carrier=#{carrier}" %></li>
    <% end %>
  </ul>
</div>

<div id="sub-header">
  <div class="container">
    <div class="col-md-8 col-md-offset-2">
      <% if @carriers.present? %>
        <%= link_to "#", class: "toggle-filter" do %>
          <i class="fa fa-sitemap <%= "selected" if filter_on %>" aria-hidden="true"></i>
        <% end %>
      <% end %>

      <div class="thumbnail-and-list">
        <%= link_to manuals_path(@cleaned_params) do %>
          <i class="fa fa-file-image-o <%= "selected" if @index_selected %>" aria-hidden="true"></i>
        <% end %>

        <%= link_to list_manuals_path(@cleaned_params) do %>
          <i class="fa fa-list-ul <%= "selected" if @list_selected %>" aria-hidden="true"></i>
        <% end %>
      </div>

      <% if filter_on %>
        <p>
          Filtering
          <% if params[:carrier].present? %>
            Carrier: <em><%= params[:carrier] %></em>
          <% elsif params[:make].present? %>
            Make: <em><%= params[:make] %></em>
          <% else %>
            Mode: <em><%= params[:mode] %></em>
          <% end %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/manuals/_form.html.erb
<div class="container">
  <div class="col-sm-6 col-sm-offset-3">
    <%= form_for [manual] do |form| %>

      <div class="form-group">
        <%= form.label :mode %>
        <%= form.select :mode, options_for_select(Manual::MODES, @manual.mode), {}, { id: :manual_mode, class: "form-control input-lg" } %>
        <%= error_messages_for(@manual, :mode) %>
      </div>

      <div class="form-group">
        <%= form.label :carrier %>
        <%= form.text_field :carrier, id: :manual_carrier, class: "form-control input-lg" %>
        <%= error_messages_for(@manual, :carrier) %>
      </div>

      <div class="form-group">
        <%= form.label :make %>
        <%= form.text_field :make, id: :manual_make, class: "form-control input-lg" %>
        <%= error_messages_for(@manual, :make) %>
      </div>

      <div class="form-group">
        <%= form.label :model %>
        <%= form.text_field :model, id: :manual_model, class: "form-control input-lg" %>
        <%= error_messages_for(@manual, :model) %>
      </div>

      <div class="form-group">
        <%= form.label :revision %>
        <%= form.text_field :revision, id: :manual_revision, class: "form-control input-lg" %>
      </div>

      <div class="form-group">
        <%= form.label :notes %>
        <%= form.text_area :notes, id: :manual_notes, class: "form-control input-lg" %>
      </div>

      <div class="form-group">
        <%= form.label :photo %>

        <% if @manual.photo.present? %>
          <%= image_tag(@manual.photo.url(:medium), class: "img-responsive") %>
        <% end %>

        <%= form.file_field :photo, id: :manual_photo, class: "form-control input-lg" %>
      </div>

      <div class="actions">
        <button type="submit" class="btn btn-info btn-lg">SAVE</button>
      </div>
    <% end %>

    <% unless action_name == "new" %>
      <hr/>
      <%= button_to 'DELETE', manual_path(@manual), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-lg btn-danger" %>
    <% end %>
  </div>
</div>

app/views/manuals/about.html.erb
<div id="about">
  <div class="container">
    <div class="col-md-8 col-md-offset-2">
      <h4>What's up with all the safety manuals, Eli?</h4>
      <p>On March 1st, 2009, I was boarding a Qantas Airlines flight from Syndey to LA on the way home from my second season working at <%= link_to "McMurdo Station in Antarctica", "https://eliduke.com/photography/antarctica/", target: "_blank" %>. It was late and I was tired. I sat down in my seat and pulled out the in-flight safety manual for something to stare at blankly. It only took a few minutes before I found myself a hearty chuckle.
      <%= image_tag "qantas.jpg", title: "Qantas Airlines: NO FURBIES", alt: "Qantas Airlines: NO FURBIES", class: "img-responsive" %>
      <p>Do you see it?</p>
      <p>Nestled in there amoungst all the normal things that everyone knows you aren't supposed to use on a flight, like, a radio or a walkie-talkie, was a cute little <strong>FURBY</strong>. "Oh geez," I must have said to myself at the time. And right there next to the Furby was a <%= link_to "Tamagotchi", "https://en.wikipedia.org/wiki/Tamagotchi", target: "_blank" %>!</p>
      <%= image_tag "furby.jpg", title: "Qantas Airlines: NO FURBIES", alt: "Qantas Airlines: NO FURBIES", class: "img-responsive" %>
      <p>I couldn't help but picture a hypothetical passenger boarding their long flight from Syndey to somewhere in SE Asia, settling in, pulling out their Furby, and then one of the flight attendants walking by, shaking their head, and then pointing at the in-flight safety manual. <strong>So fucking funny</strong>. So fucking funny, in fact, that I slipped that safety manual directly into my backpack.</p>
      <p>And so began my collection of in-flight safety manuals.</p>
      <p>They are such an interesting exercise in design, primarily because they don't usually contain many words. They have to convey all of the important safety information using only pictures! Each one has its own little charm and character, but there are similarities across the board.</p>
      <p>For example, from now on you'll probably start noticing that in all the sections about inflattable rafts, there's always a circle-with-a-line-through-it around a high-heeled shoe, because, you know, they could pop the raft and then everyone dies. You'll also notice how strange the children always look, like tiny old people:</p>
      <%= image_tag "weird-mom-and-kid.jpg", title: "Weird kid standing on a plane", alt: "Weird kid standing on a plane", class: "img-responsive" %>
      <p>That arrow and strap through the legs feels weird to me. And that hands-on-the-shoulders longing stare deep into his mother's eyes? How are they so calm?! The plane is about to or has already crashed!</p>
      <%= image_tag "weird-kid.jpg", title: "Weird kid on a plane", alt: "Weird kid on a plane", class: "img-responsive" %>
      <p>That little guy reminds me of me when I was his age. So dapper.</p>
      <p>Anyhoo, if you ever find yourself on a flight with a safety manual in your hand and you're wondering, "Does Eli have this one?" you can always just check the <%= link_to "Master List", list_manuals_path %>. If I don't yet, feel free to snag it for me.</p>
      <p class="emoji">😘✈️🤓✈️😘</p>
    </div>
  </div>
</div>

app/views/manuals/edit.html.erb
<h3>Editing Manual</h3>

<%= render 'form', manual: @manual %>

app/views/manuals/index.html.erb
<div id="index">
  <div class="container">
    <div class="flex-container">
      <% @manuals.each do |manual| %>
        <div class="flex-item">
          <%= link_to manual do %>
            <h2><%= manual.carrier %></h2>
            <p class="make_and_model"><%= manual.make %> <%= manual.model %></p>
          <% end %>

          <%= image_tag(manual.photo.url(:small), class: "img-responsive") %>

          <p class="meta">
            <%= manual.created_at.strftime("%B %-d, %Y") %> /
            <%= link_to "Edit", edit_manual_path(manual) %>
          </p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/manuals/list.html.erb
<h3>Master List</h3>

<div class="container">
  <div class="col-md-8 col-md-offset-2">
    <table class="table">
      <thead class="thead-inverse">
        <tr>
          <th style="width: 30px"></th>
          <th>Carrier</th>
          <th>Make &amp; Model</th>
          <th style="width: 30px"></th>
        </tr>
      </thead>

      <tbody>
        <% @manuals.each do |manual| %>
          <tr>
            <td>
              <%= link_to manual do %>
                <%= fa_icon "file-image-o" %>
              <% end %>
            </td>

            <td><%= manual.carrier %></td>
            <td><%= manual.make %> <%= manual.model %></td>

            <td>
              <%= link_to edit_manual_path(manual) do %>
                <%= fa_icon "edit" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/manuals/new.html.erb
<h3>New Manual</h3>

<%= render 'form', manual: @manual %>

app/views/manuals/show.html.erb
<div id="show">
  <div class="container">
    <div class="col-sm-6 col-sm-offset-3">
      <h2><%= @manual.carrier %></h2>
      <p class="make_and_model"><%= @manual.make %> <%= @manual.model %></p>

      <p class="notes">
        <%= simple_format(@manual.notes) %>
      </p>

      <%= image_tag(@manual.photo.url(:medium), class: "img-responsive") %>

      <p class="meta">
        <%= @manual.created_at.strftime("%B %-d, %Y") %> /
        <%= link_to "Edit", edit_manual_path(@manual) %>
      </p>
    </div>
  </div>
</div>